
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  
  port: 3306


test:
  <<: *default
  database: engineerQA_test
  host: localhost
  

development:
  <<: *default
  database: engineerQA_development
  host: localhost



production:
  database: engidoor_production
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: admin
  password: password
  host: engidoor-database-3.cmdexsnlk4dz.ap-northeast-1.rds.amazonaws.com
  port: 3306

